# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eca0a49cbec5b48483769d3419560d32"
name = "I95dev NetSuite Integration"
application_url = "https://i95dev-netsuite.vercel.app"
embedded = true
handle = "i95dev-netsuite-integration-1"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-07" 

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://i95dev-netsuite.vercel.app/auth/callback",
  "https://i95dev-netsuite.vercel.app/auth/shopify/callback",
  "https://i95dev-netsuite.vercel.app/api/auth/callback"
]

[pos]
embedded = false


